site_name: CSC 3220 Winter 2019 Syllabus
theme: readthedocs

markdown_extensions:
  - footnotes
  - tables

pages:
  - Welcome: index.md
  - Instructor Information and Contact: contact.md
  - Course Description and Objectives: overview.md
  - Textbook, Media, Resources: textbook.md
  - Assignment and Grading Policies: grading.md 
  - Attendence and Classroom Policies: classroom.md
  - CS/IS Learning Outcomes: outcomes.md
